-- Tabela que armazena informações de operadoras ativas
CREATE TABLE OPERADORAS_ATIVAS(
	REGISTRO_ANS INT PRIMARY KEY,
	CNPJ VARCHAR(14),
	RAZAO_SOCIAL VARCHAR(150),
	NOME_FANTASIA VARCHAR(150),
	MODALIDADE VARCHAR(150),
	LOGRADOURO VARCHAR(150),
	NUMERO VARCHAR(50),
	COMPLEMENTO VARCHAR(150),
	BAIRRO VARCHAR(150),
	CIDADE VARCHAR(150),
	UF VARCHAR(2),
	CEP VARCHAR(8),
	DDD VARCHAR(2),
	TELEFONE VARCHAR(40),
	FAX VARCHAR(40),
	ENDERECO_ELETRONICO VARCHAR(150),
	REPRESENTANTE VARCHAR(150),
	CARGO_REPRESENTANTE VARCHAR(150),
	REGIAO_DE_COMERCIALIZACAO VARCHAR(150),
	DATA_REGISTRO_ANS DATE
);

-- Tabela temporária para armazenar dados temporários
CREATE TEMPORARY TABLE TEMP_DADOS(
	DATA_REFERENCIA DATE,
	REG_ANS INT,
	CD_CONTA_CONTABIL VARCHAR(20),
	DESCRICAO VARCHAR(200),
	VALOR_SALDO_INICIAL VARCHAR(20),
	VALOR_SALDO_FINAL VARCHAR(20)
);

-- Tabela permanente para armazenar os dados transformados
CREATE TABLE DEMONSTRACOES_CONTABEIS(
	ID SERIAL PRIMARY KEY,
	DATA_REFERENCIA DATE,
	REG_ANS INT NOT NULL,
	CD_CONTA_CONTABIL VARCHAR(20),
	DESCRICAO VARCHAR(200),
	VALOR_SALDO_INICIAL NUMERIC,
	VALOR_SALDO_FINAL NUMERIC
);

-- Copiando dados do arquivo CSV para a tabela OPERADORAS_ATIVAS
COPY OPERADORAS_ATIVAS FROM 'C:\Program Files\PostgreSQL\16\data\Relatorio_cadop.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';

-- Copiando dados dos aquivos CSV de 2022 para a tabela TEMP_DADOS
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\1T2022.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\2T2022.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\3T2022.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\4T2022.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';

-- Copiando dados dos aquivos CSV de 2023 para a tabela TEMP_DADOS
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\1T2023.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\2T2023.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';
COPY TEMP_DADOS FROM 'C:\Program Files\PostgreSQL\16\data\3T2023.csv'  DELIMITER ';' CSV HEADER ENCODING 'ISO-8859-1';

-- Realizando a transformação nos dados da tabela TEMP_DADOS, trocando a "," pelo "."
UPDATE TEMP_DADOS
SET VALOR_SALDO_INICIAL = REPLACE(VALOR_SALDO_INICIAL, ',', '.'),
	VALOR_SALDO_FINAL = REPLACE(VALOR_SALDO_FINAL, ',', '.');
	
-- Inserindo os dados transformados na tabela permanente DEMONSTRACOES_CONTABEIS
INSERT INTO DEMONSTRACOES_CONTABEIS (DATA_REFERENCIA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VALOR_SALDO_INICIAL, VALOR_SALDO_FINAL)
SELECT
	DATA_REFERENCIA,
	REG_ANS,
	CD_CONTA_CONTABIL,
	DESCRICAO,
	CAST(VALOR_SALDO_INICIAL AS NUMERIC),
	CAST(VALOR_SALDO_FINAL AS NUMERIC)
FROM TEMP_DADOS;

-- Removendo a tabela temporária TEMP_DADOS
DROP TABLE TEMP_DADOS;

-- as 10 operadoras com maiores despesas em "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último trimestre
SELECT OA.RAZAO_SOCIAL, SUM(DC.VALOR_SALDO_FINAL)
FROM DEMONSTRACOES_CONTABEIS DC
INNER JOIN OPERADORAS_ATIVAS OA ON OA.REGISTRO_ANS = DC.REG_ANS
WHERE DC.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
	AND DC.DATA_REFERENCIA BETWEEN '2023-10-01' AND '2023-12-31'
GROUP BY OA.RAZAO_SOCIAL
ORDER BY SUM(DC.VALOR_SALDO_FINAL) DESC
LIMIT 10;

-- as 10 operadoras com maiores despesas nessa categoria no último ano
SELECT OA.RAZAO_SOCIAL, SUM(DC.VALOR_SALDO_FINAL)
FROM DEMONSTRACOES_CONTABEIS DC
INNER JOIN OPERADORAS_ATIVAS OA ON OA.REGISTRO_ANS = DC.REG_ANS
WHERE DC.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
	AND DC.DATA_REFERENCIA BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY OA.RAZAO_SOCIAL
ORDER BY SUM(DC.VALOR_SALDO_FINAL) DESC
LIMIT 10;



